"use client";

console.warn(
  "⚠️ Avoid importing components from 'index.js' for better performance. This practice is deprecated and may be removed in the future."
);

export * as _Builtin from "./_Builtin";
export * from "./Agenda24Author";
export * from "./Agenda24Blocker";
export * from "./Agenda24Item";
export * from "./Agenda24ItemEmpty";
export * from "./AgendaGridItem";
export * from "./AlertLastTickets";
export * from "./AwardsNav";
export * from "./AwardsNavbar";
export * from "./AwardsSingleTile";
export * from "./BgHome";
export * from "./ButtonIcon";
export * from "./C4SDivider";
export * from "./CompoenntChipIcon";
export * from "./ComponentChip";
export * from "./ConferencePackage";
export * from "./Contact";
export * from "./Cta24Section";
export * from "./CursorFormJury";
export * from "./CursorHome";
export * from "./CursorJury";
export * from "./CursorPastProject";
export * from "./CursrorSectionJuryPeople";
export * from "./devlink";
export * from "./devlinkContext";
export * from "./DevLinkProvider";
export * from "./DividerLinearGradient";
export * from "./DownloadApp";
export * from "./DraftCode";
export * from "./FeedbacSwiper";
export * from "./Footer";
export * from "./Footer24";
export * from "./Footer24Small";
export * from "./FormInput";
export * from "./GlobalCustomCode";
export * from "./HeroAwards";
export * from "./InfoBar";
export * from "./InfopackItem";
export * from "./interactions";
export * from "./Nav24";
export * from "./Navbar";
export * from "./Navbar2024New";
export * from "./NetworkingPackage";
export * from "./OnlinePackage";
export * from "./PageGlobals";
export * from "./PartyPlus1Form";
export * from "./Pitchmebaby";
export * from "./Section24Gallery";
export * from "./Section25Gallery";
export * from "./SectionAudience";
export * from "./SectionHome24Blocker";
export * from "./SectionHome24Companies";
export * from "./SectionHome24Numbers";
export * from "./SectionRegisterBlocker";
export * from "./SliderFeedbackItem";
export * from "./SsSectionStructure";
export * from "./StartupCompanies";
export * from "./StartupStage";
export * from "./Tag";
export * from "./TicketsFaqItem";
export * from "./TicketsPlnSingl";
export * from "./TomAwards";
export * from "./utils";
export * from "./VoteItem";
export * from "./Ways25Blocker";
export * from "./Ways25Button";
export * from "./Ways25CommunitySlide";
export * from "./Ways25Form";
export * from "./Ways25Partner";
export * from "./Ways25PreviousItem";
export * from "./Ways25Tag";
export * from "./Ways25TagIcon";
